spring.datasource.url=jdbc:postgresql://localhost:5432/jwtdemo
spring.datasource.username=thanish_shetty
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret-key=BdesYEYd54m9oKO3RR40wG6gMNqNYp4Gk7h8s1Yib0E=
security.jwt.expiration-time=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shettythanish202@gmail.com
spring.mail.password=rzoa yscs zevu grlm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG
